# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hrtf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhrtf.proto\x12\x04hrtf\"-\n\x0bHrtfAzimuth\x12\r\n\x05\x61ngle\x18\x01 \x02(\x01\x12\x0f\n\x07impulse\x18\x02 \x03(\x02\"C\n\rHrtfElevation\x12\r\n\x05\x61ngle\x18\x01 \x02(\x01\x12#\n\x08\x61zimuths\x18\x02 \x03(\x0b\x32\x11.hrtf.HrtfAzimuth\"6\n\x0bHrtfDataset\x12\'\n\nelevations\x18\x01 \x03(\x0b\x32\x13.hrtf.HrtfElevation')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hrtf_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HRTFAZIMUTH._serialized_start=20
  _HRTFAZIMUTH._serialized_end=65
  _HRTFELEVATION._serialized_start=67
  _HRTFELEVATION._serialized_end=134
  _HRTFDATASET._serialized_start=136
  _HRTFDATASET._serialized_end=190
# @@protoc_insertion_point(module_scope)
