[workspace]
members = ["crates/*"]

[workspace.dependencies]
bytes = "1.3.0"
cond_tree = { path = "crates/cond_tree" }
cond_tree_macro = { path = "crates/cond_tree_macro" }
derive_more = "0.99.17"
itertools = "0.10.5"
paste = "1.0.9"
prost = "0.11.2"
prost-build = "0.11.2"
smallvec = "1.10.0"
synthizer_protos = { path = "crates/protos" }
thiserror = "1.0.37"

