[workspace]
members = ["crates/*"]

[workspace.dependencies]
bytes = "1.3.0"
cond_tree = { path = "crates/cond_tree" }
cond_tree_macro = { path = "crates/cond_tree_macro" }
itertools = "0.10.5"
prost = "0.11.2"
prost-build = "0.11.2"
