[workspace]
members = ["crates/*"]

[workspace.dependencies]
ahash = "0.8.3"
arc-swap = "1.6.0"
arrayvec = "0.7.2"
atomic_refcell = "0.1.9"
cc = "1.0.79"
criterion = "0.4.0"
crossbeam = "0.8.2"
derive_more = "0.99.17"
env_logger = "0.10.0"
itertools = "0.10.5"
lazy_static = "1.4.0"
log = "0.4.17"
loom = "0.5.6"
num = "0.4.0"
paste = "1.0.9"
petgraph = "0.6.3"
primes = "0.3.0"
proptest = "1.1.0"
prost = "0.11.2"
prost-build = "0.11.2"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
sharded-slab = "0.1.4"
smallvec = "1.10.0"
supermatch = { path = "crates/supermatch" }
supermatch_macro = { path = "crates/supermatch_macro" }
synthizer_protos = { path = "crates/protos" }
thiserror = "1.0.37"

[profile.bench]
lto = true
