[workspace]
members = ["crates/*"]

[workspace.dependencies]
arrayvec = "0.7.2"
atomic_refcell = "0.1.9"
criterion = "0.4.0"
crossbeam = "0.8.2"
derive_more = "0.99.17"
itertools = "0.10.5"
loom = "0.5.6"
num = "0.4.0"
paste = "1.0.9"
prost = "0.11.2"
prost-build = "0.11.2"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
sharded-slab = "0.1.4"
smallvec = "1.10.0"
supermatch = { path = "crates/supermatch" }
supermatch_macro = { path = "crates/supermatch_macro" }
synthizer_protos = { path = "crates/protos" }
thiserror = "1.0.37"
