[package]
name = "cond_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cond_tree_macro.workspace = true
derive_more = "0.99.17"
