on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Run tests'
      shell: bash
      run: |
        set -ex
        cd $GITHUB_WORKSPACE
        cargo check --all-targets --all-features
        cargo test --all-features
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
          - os: macos-latest

  test_windows:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Configure MSVC Environment Variables
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set > %GITHUB_ENV%
    - name: 'Run tests'
      shell: cmd
      run: |
        cd %GITHUB_WORKSPACE%
        cargo check --all-targets --all-features
        cargo test --all-features
