[package]
name = "synthizer_macros_internal"
version = "0.1.0"
edition = "2021"


[lib]
proc-macro = true


[dependencies]
darling.workspace = true
proc-macro-error.workspace = true
quote.workspace = true
syn.workspace = true
